services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!  # Hardcode because debugging
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrongPassword123!" -Q "SELECT 1" || exit 1
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 120s

  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=HumaneSociety
      - DB_USER=sa
      - DB_PASSWORD=YourStrongPassword123!
      - MIGRATION_DIR=/app/migrations/mssql
    restart: always
    # Avoid healthcheck dependency and use a custom entrypoint script instead
    entrypoint: ["sh", "-c", "sleep 30 && /app/server"]

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mssql-data: