services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!  # Hardcode because debugging
      - MSSQL_PID=Developer
    # ports:
    #   - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    # healthcheck fails no matter what I do for some reason. I need to fix this in the future.
    # healthcheck:
    #   test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrongPassword123!" -Q "SELECT 1" -b -o /dev/null || exit 1
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 30s

  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=HumaneSociety
      - DB_USER=sa
      - DB_PASSWORD=YourStrongPassword123!
      - DB_MAX_OPEN_CONNS=25
      - DB_MAX_IDLE_CONNS=10
      - DB_CONN_MAX_LIFE_TIME=5
      - MIGRATION_DIR=/app/migrations/mssql
      # TODO: Change the JWT_SECRET once in production
      - JWT_SECRET=9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a
    # I do not know why but depends on service healthy always fails even though database connection works fine with backend
    # depends_on:
    #   db:
    #     condition: service_healthy
    restart: on-failure
    entrypoint: ["/bin/sh", "-c", "sleep 30 && /app/server"]

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mssql-data: